return {
  --   {
  --     "GCBallesteros/NotebookNavigator.nvim",
  --     keys = {
  --       {
  --         "n",
  --         "]h",
  --         function()
  --           require("notebook-navigator").move_cell("d")
  --         end,
  --       },
  --       {
  --         "n",
  --         "[h",
  --         function()
  --           require("notebook-navigator").move_cell("u")
  --         end,
  --       },
  --       { "n", "<leader>X", "<cmd>lua require('notebook-navigator').run_cell()<cr>" },
  --       { "n", "<leader>x", "<cmd>lua require('notebook-navigator').run_and_move()<cr>" },
  --     },
  --     dependencies = {
  --       "echasnovski/mini.comment",
  --       "hkupty/iron.nvim", -- repl provider
  --       -- "akinsho/toggleterm.nvim", -- alternative repl provider
  --       -- "benlubas/molten-nvim", -- alternative repl provider
  --       "anuvyklack/hydra.nvim",
  --     },
  --     event = "VeryLazy",
  --     opts = {
  --       { activate_hydra_keys = "<leader>h" },
  --     },
  --   },
}
